# torchdtcc config.yaml

model:
  input_dim: 1
  num_layers: 3
  num_clusters: 3
  hidden_dims: [64, 64, 64]  # Simplified architecture with consistent dimensions
  dilation_rates: [1, 4, 16]  # These look good
  tau_I: 0.1  # Lower temperature for sharper instance contrasts
  tau_C: 0.2  # Lower temperature for cluster contrasts
  stable_svd: false

trainer:
  save_path: "dtcc_model_{}.pth"
  learning_rate: 0.001  # Lower learning rate for stability
  weight_decay: 1e-4  # Add light regularization
  lambda_cd: 5.0
  num_epochs: 500
  update_interval: 5  # This is reasonable
  gradient_clip: 5.0 
  mlflow:
    # databricks example. databricks requires this scheme for experiment name
    experiment: "/Users/first.last@companydomain.com/my_experiment_name"
    run: 'my_run_1'

data:
  path: "./data/plane/"
  batch_size: 64
  normalize: true 


output:
  soft_clusters: "soft_clusters.npy"
  hard_clusters_argmax: "hard_clusters_argmax.npy"
  hard_clusters_kmeans: "hard_clusters_kmeans.npy"

device: "cuda"  # or "cpu"